import { describe, expect, test } from "vitest"
import { createLayouter } from "./layout"
import type { GraphRow, Revision } from "./types"

// Golden parity with Git Extensions' RevisionGraph.
//
// The fixtures under __fixtures__/ge are generated by tools/ge-parity/extract.mjs
// from GE's own RevisionGraphTests snapshots (*.verified.txt). Each fixture
// carries the revisions fed to RevisionGraph, the settings the C# test used,
// and the ASCII rendering GE's AsciiGraphFor produced. We lay the same
// revisions out with PowerGit's layouter, render the rows with a port of
// AsciiGraphFor (below) and compare the text verbatim: node lane, which lanes
// carry a segment, and where every segment goes on the next row.
//
// Fixtures in KNOWN_DIVERGENCES are laid out and rendered too, but their
// assertion is inverted: they must still differ from GE. When one starts to
// match, the test fails so the entry gets removed and the fixture protected.

type GeFixture = {
  name: string
  source: { test: string; verifiedFile: string; spec: string; order: string }
  settings: { mergeGraphLanesHavingCommonParent: boolean; straightenGraphDiagonals: boolean }
  revisions: { id: string; parents: string[]; label: string }[]
  expectedRows: { id: string; lane: number; laneCount: number; occupiedLanes: number[] }[]
  expectedAscii: string[]
}

const fixtures = Object.values(
  import.meta.glob<{ default: GeFixture }>("./__fixtures__/ge/*.json", { eager: true }),
).map((m) => m.default)

/**
 * Fixtures whose GE rendering PowerGit does not reproduce, with the reason.
 * PowerGit ports RevisionGraph.BuildOrderedRowCache + RevisionGraphRow.BuildSegmentLanes
 * with MergeGraphLanesHavingCommonParent fixed to true. It does not port
 * StraightenLanes / StraightenDiagonals (a look-ahead post-pass that moves
 * already-laid-out rows, incompatible with the append-only worker protocol)
 * nor the ReduceGraphCrossings segment ordering GE enables when
 * MergeGraphLanesHavingCommonParent is false. For every merge=true entry
 * below, PowerGit's rendering equals GE's layout before StraightenLanes ran
 * (checked by hand when the map was written).
 */
const NO_MERGE = "MergeGraphLanesHavingCommonParent=false → GE orders start segments (ReduceGraphCrossings); PowerGit hard-codes merge=true"
const STRAIGHTEN = "GE StraightenLanes post-pass moves lanes to avoid a one-row jog; PowerGit has no straightening pass"
const DIAGONALS = "StraightenGraphDiagonals=true → GE StraightenDiagonals post-pass; PowerGit has no straightening pass"
const KNOWN_DIVERGENCES: Record<string, string> = {
  "SegmentsAreStraightened_merge=false": NO_MERGE,
  "SegmentsAreStraightened_merge=true": STRAIGHTEN,
  "SegmentsWithCommitsAreStraightened_merge=false": NO_MERGE,
  "SegmentsWithCommitsAreStraightened_merge=true": STRAIGHTEN,
  "SegmentsWithOutgoingSecondaryMergesAreNotStraightened_merge=false": NO_MERGE,
  "SegmentsWithIncomingMergesAreStraightened_merge=false": NO_MERGE,
  "SegmentsWithIncomingMergesAreStraightened_merge=true": STRAIGHTEN,
  "SegmentsAreStraightenedAlthoughThisCausesWidthIncrease_merge=false": NO_MERGE,
  "SegmentsAreStraightenedAlthoughThisCausesWidthIncrease_merge=true": STRAIGHTEN,
  "SegmentsWithOutgoingPrimaryMergesAreStraightened_merge=false": NO_MERGE,
  "SegmentsWithOutgoingPrimaryMergesAreStraightened_merge=true": STRAIGHTEN,
  "SegmentsAreNotStraightenedIfThisCausesAShiftForPrimarySegment_merge=false": NO_MERGE,
  "SegmentsAreNotStraightenedIfThisCausesAShiftForPrimarySegment_merge=true": STRAIGHTEN,
  "SegmentsAreNotStraightenedOverMultiLaneCrossings_NoMergeGraphLanesHavingCommonParent": NO_MERGE,
  "SegmentsAreNotStraightenedOverMultiLaneCrossings_NoMergeGraphLanesHavingCommonParent_StraightenGraphDiagonals": DIAGONALS,
  TurnMultiLaneCrossingsIntoDiagonals_1: DIAGONALS,
  TurnMultiLaneCrossingsIntoDiagonals_2: DIAGONALS,
  TurnMultiLaneCrossingsIntoDiagonals_3: DIAGONALS,
  UnfoldOneLaneShiftsToDiagonals_1: DIAGONALS,
  UnfoldOneLaneShiftsToDiagonals_2: DIAGONALS,
  UnfoldOneLaneShiftsToDiagonals_3: DIAGONALS,
  UnfoldOneLaneShiftsToDiagonals_4: DIAGONALS,
  DoNotUnfoldOneLaneShiftFollowedByDiagonal_1: DIAGONALS,
  DoNotUnfoldOneLaneShiftFollowedByDiagonal_2: DIAGONALS,
  DoNotUnfoldOneLaneShiftFollowedByDiagonal_3: DIAGONALS,
  DoNotUnfoldOneLaneShiftFollowedByDiagonal_4: DIAGONALS,
  DoNotUnfoldOneLaneShiftFollowedByDiagonal_5: DIAGONALS,
  JoinMultiLaneCrossings_1: DIAGONALS,
  JoinMultiLaneCrossings_2: DIAGONALS,
  JoinMultiLaneCrossings_3: DIAGONALS,
  JoinMultiLaneCrossings_4: DIAGONALS,
  DoNotJoinMultiLaneCrossings_1: DIAGONALS,
  DoNotJoinMultiLaneCrossings_2: DIAGONALS,
}

function toRevisions(fixture: GeFixture): Revision[] {
  return fixture.revisions.map((r) => ({
    id: r.id,
    parents: r.parents,
    message: r.label,
    author: "ge",
    date: "0",
    refs: [],
  }))
}

function laneCount(row: GraphRow): number {
  return row.segments.reduce((m, s) => Math.max(m, s.lane + 1), row.lane + 1)
}

/** Port of RevisionGraphTests.AsciiGraphFor over PowerGit rows. */
function asciiGraphFor(rows: GraphRow[], labels: Map<string, string>): string[] {
  const graph: string[] = []
  for (let rowIndex = 0; rowIndex < rows.length; rowIndex++) {
    const row = rows[rowIndex]
    const line = new Array<string>(laneCount(row) * 2 + 1).fill(" ")
    for (const segment of row.segments) line[segment.lane * 2] = "|"
    line[row.lane * 2] = labels.get(row.rev.id) ?? "*"
    graph.push(line.join("").trimEnd())

    const nextRow = rows[rowIndex + 1]
    if (!nextRow) break

    const between = new Array<string>(Math.max(laneCount(row), laneCount(nextRow)) * 2 + 1).fill(" ")
    const nextLane = new Map(nextRow.segments.map((s) => [s.id, s.lane]))
    const actions: Array<() => void> = []
    for (const segment of row.segments) {
      const fromPos = segment.lane * 2
      const to = nextLane.get(segment.id)
      if (to === undefined) continue // segment ends at this row
      const toPos = to * 2
      if (toPos === fromPos) {
        actions.push(() => (between[fromPos] = "|"))
      } else if (toPos === fromPos + 2) {
        actions.push(() => (between[fromPos + 1] = between[fromPos + 1] === "/" ? "X" : "\\"))
      } else if (toPos === fromPos - 2) {
        actions.push(() => (between[fromPos - 1] = between[fromPos - 1] === "\\" ? "X" : "/"))
      } else if (toPos > fromPos) {
        between[fromPos + 1] = "`"
        between[toPos] = "ˎ"
        for (let pos = fromPos + 2; pos < toPos; pos++) between[pos] = "-"
      } else {
        between[fromPos - 1] = "´"
        between[toPos] = ","
        for (let pos = toPos + 1; pos < fromPos - 1; pos++) between[pos] = "-"
      }
    }
    for (const action of actions) action()
    graph.push(between.join("").trimEnd())
  }
  return graph
}

describe("Git Extensions RevisionGraph golden fixtures", () => {
  test("fixtures are present", () => {
    expect(fixtures.length).toBeGreaterThan(0)
    for (const name of Object.keys(KNOWN_DIVERGENCES)) {
      expect(fixtures.map((f) => f.name), `KNOWN_DIVERGENCES entry without fixture: ${name}`).toContain(name)
    }
  })

  for (const fixture of fixtures) {
    const labels = new Map(fixture.revisions.map((r) => [r.id, r.label]))
    const divergence = KNOWN_DIVERGENCES[fixture.name]

    test(`${fixture.name}${divergence ? " [known divergence]" : ""}`, () => {
      const rows = createLayouter().append(toRevisions(fixture))
      expect(rows.map((r) => r.rev.id)).toEqual(fixture.expectedRows.map((r) => r.id))
      const rendered = asciiGraphFor(rows, labels)

      if (divergence) {
        expect(rendered, `${fixture.name} now matches GE — drop it from KNOWN_DIVERGENCES (${divergence})`).not.toEqual(
          fixture.expectedAscii,
        )
        return
      }

      expect(rows.map((r) => r.lane)).toEqual(fixture.expectedRows.map((r) => r.lane))
      // occupiedLanes = lanes drawn as '|' on the commit line, i.e. every lane
      // carrying a segment except the node's own lane (the label overwrites it).
      expect(
        rows.map((r) => [...new Set(r.segments.map((s) => s.lane))].filter((l) => l !== r.lane).sort((a, b) => a - b)),
      ).toEqual(fixture.expectedRows.map((r) => r.occupiedLanes))
      expect(rendered.join("\n")).toEqual(fixture.expectedAscii.join("\n"))
    })
  }
})
